import {
  Department,
  Course,
  StudentRecord,
  FacultyRecord,
  AttendanceRecord,
  ExamSchedule,
  TimetableSlot,
} from '../types/academic';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-cse',
    code: 'CSE',
    name: 'Computer Science & Engineering',
    headOfDepartment: 'Prof. Sarah Jenkins',
    headFacultyId: 'fac-001',
    facultyCount: 24,
    studentCount: 480,
    coursesCount: 32,
    budget: '$1.25M',
    labCount: 8,
    establishedYear: 2008,
    description: 'Specializing in AI, distributed computing, cyber security, and software engineering.',
  },
  {
    id: 'dept-ai',
    code: 'AI-DS',
    name: 'Artificial Intelligence & Data Science',
    headOfDepartment: 'Dr. Evelyn Vance',
    headFacultyId: 'fac-002',
    facultyCount: 18,
    studentCount: 320,
    coursesCount: 24,
    budget: '$1.10M',
    labCount: 6,
    establishedYear: 2018,
    description: 'Focusing on neural networks, natural language processing, autonomous systems, and big data analytics.',
  },
  {
    id: 'dept-ece',
    code: 'ECE',
    name: 'Electronics & Communication Engineering',
    headOfDepartment: 'Dr. Rajesh Nair',
    headFacultyId: 'fac-003',
    facultyCount: 20,
    studentCount: 380,
    coursesCount: 28,
    budget: '$950K',
    labCount: 7,
    establishedYear: 2009,
    description: 'Covering VLSI, embedded hardware, wireless signal processing, and robotics controls.',
  },
  {
    id: 'dept-mech',
    code: 'MECH',
    name: 'Mechanical Engineering',
    headOfDepartment: 'Prof. Robert Taylor',
    headFacultyId: 'fac-004',
    facultyCount: 16,
    studentCount: 300,
    coursesCount: 22,
    budget: '$880K',
    labCount: 5,
    establishedYear: 2010,
    description: 'Thermal dynamics, computer-aided manufacturing, fluid mechanics, and mechatronics systems.',
  },
  {
    id: 'dept-civil',
    code: 'CIVIL',
    name: 'Civil & Environmental Engineering',
    headOfDepartment: 'Dr. Ananya Roy',
    headFacultyId: 'fac-005',
    facultyCount: 14,
    studentCount: 240,
    coursesCount: 18,
    budget: '$750K',
    labCount: 4,
    establishedYear: 2012,
    description: 'Structural mechanics, smart urban infrastructure, transportation, and environmental sustainability.',
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'crs-cs301',
    code: 'CS301',
    title: 'Distributed Systems & Cloud Architecture',
    departmentCode: 'CSE',
    credits: 4,
    semester: 6,
    instructorId: 'fac-001',
    instructorName: 'Prof. Sarah Jenkins',
    capacity: 60,
    enrolledCount: 58,
    description: 'Consensus protocols, Raft, Paxos, fault tolerance, microservices architecture, and cloud scaling.',
    syllabus: [
      'Module 1: Distributed Consistency Models & CAP Theorem',
      'Module 2: Leader Election & Consensus Protocols (Raft/Paxos)',
      'Module 3: RPC Systems & Protocol Buffers',
      'Module 4: Container Orchestration & Kubernetes Internals',
    ],
    scheduleDays: ['Monday', 'Wednesday'],
    scheduleTime: '09:00 - 10:30 AM',
    room: 'Tech Hall 102',
    status: 'active',
  },
  {
    id: 'crs-cs304',
    code: 'CS304',
    title: 'Artificial Intelligence & Neural Networks',
    departmentCode: 'AI-DS',
    credits: 4,
    semester: 6,
    instructorId: 'fac-002',
    instructorName: 'Dr. Evelyn Vance',
    capacity: 60,
    enrolledCount: 55,
    description: 'Deep Learning, Transformers, Convolutional Networks, Gradient Descent, and Reinforcement Learning.',
    syllabus: [
      'Module 1: Multilayer Perceptrons & Backpropagation Math',
      'Module 2: Convolutional Neural Nets for Computer Vision',
      'Module 3: Sequence Modeling & Transformer Architectures',
      'Module 4: Reinforcement Learning & Q-Learning',
    ],
    scheduleDays: ['Tuesday', 'Thursday'],
    scheduleTime: '10:30 - 12:00 PM',
    room: 'AI Lab 3',
    status: 'active',
  },
  {
    id: 'crs-cs309',
    code: 'CS309',
    title: 'Cyber Security & Ethical Hacking',
    departmentCode: 'CSE',
    credits: 3,
    semester: 6,
    instructorId: 'fac-001',
    instructorName: 'Prof. Sarah Jenkins',
    capacity: 50,
    enrolledCount: 48,
    description: 'Cryptographic algorithms, web vulnerability assessment, penetration testing, and zero-trust security.',
    syllabus: [
      'Module 1: Symmetric & Asymmetric Cryptography',
      'Module 2: Network Penetration & Packet Analysis',
      'Module 3: OWASP Top 10 Security Risks',
      'Module 4: Identity & Access Management Systems',
    ],
    scheduleDays: ['Friday'],
    scheduleTime: '01:00 - 04:00 PM',
    room: 'Cyber Lab B',
    status: 'active',
  },
  {
    id: 'crs-ec204',
    code: 'EC204',
    title: 'Embedded Systems & IoT Hardware',
    departmentCode: 'ECE',
    credits: 4,
    semester: 4,
    instructorId: 'fac-003',
    instructorName: 'Dr. Rajesh Nair',
    capacity: 55,
    enrolledCount: 52,
    description: 'ARM Cortex microcontrollers, RTOS kernel design, sensor integration, and MQTT protocols.',
    syllabus: [
      'Module 1: ARM Architecture & Assembly Basics',
      'Module 2: Interrupt Controls & Timers',
      'Module 3: Real-Time Operating Systems (FreeRTOS)',
      'Module 4: Wireless Communication Protocols (BLE/Zigbee)',
    ],
    scheduleDays: ['Monday', 'Wednesday'],
    scheduleTime: '11:00 - 12:30 PM',
    room: 'ECE Hall 204',
    status: 'active',
  },
  {
    id: 'crs-me310',
    code: 'ME310',
    title: 'Robotics & Automation Systems',
    departmentCode: 'MECH',
    credits: 3,
    semester: 6,
    instructorId: 'fac-004',
    instructorName: 'Prof. Robert Taylor',
    capacity: 45,
    enrolledCount: 40,
    description: 'Kinematics of manipulators, inverse kinematics, PID control loops, and Industrial ROS 2.',
    syllabus: [
      'Module 1: Spatial Transformations & Forward Kinematics',
      'Module 2: Jacobian Matrices & Singularities',
      'Module 3: Trajectory Planning & Actuators',
      'Module 4: Robot Operating System (ROS 2) Practical Labs',
    ],
    scheduleDays: ['Tuesday', 'Thursday'],
    scheduleTime: '02:00 - 03:30 PM',
    room: 'Robotics Bay 1',
    status: 'active',
  },
  {
    id: 'crs-ce402',
    code: 'CE402',
    title: 'Smart Infrastructure & Structural Dynamics',
    departmentCode: 'CIVIL',
    credits: 4,
    semester: 8,
    instructorId: 'fac-005',
    instructorName: 'Dr. Ananya Roy',
    capacity: 40,
    enrolledCount: 35,
    description: 'IoT structural health monitoring, seismic design principles, and eco-sustainable construction materials.',
    syllabus: [
      'Module 1: Dynamic Load Modeling & Vibration Analysis',
      'Module 2: Seismic Isolation & Energy Dissipation',
      'Module 3: Sensor Array Deployment on Bridges/Towers',
      'Module 4: Lifecycle Analysis & Carbon Neutral Materials',
    ],
    scheduleDays: ['Wednesday', 'Friday'],
    scheduleTime: '09:00 - 10:30 AM',
    room: 'Civil Design Lab',
    status: 'active',
  },
];

export const INITIAL_FACULTY: FacultyRecord[] = [
  {
    id: 'fac-001',
    employeeId: 'FAC-CSE-001',
    name: 'Prof. Sarah Jenkins',
    email: 'sarah.jenkins@luminous.edu',
    department: 'Computer Science & Engineering',
    designation: 'Head of Department',
    specialization: 'Distributed Systems & Cloud Computing',
    officeRoom: 'Tech Tower Room 402',
    phone: '+91 98803 16773',
    status: 'Active',
    coursesTaught: ['CS301', 'CS309'],
    publicationsCount: 34,
    rating: 4.9,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
  },
  {
    id: 'fac-002',
    employeeId: 'FAC-AI-002',
    name: 'Dr. Evelyn Vance',
    email: 'evelyn.vance@luminous.edu',
    department: 'Artificial Intelligence & Data Science',
    designation: 'Professor',
    specialization: 'Neural Networks & Deep Learning',
    officeRoom: 'AI Research Block 301',
    phone: '+91 98450 19283',
    status: 'Active',
    coursesTaught: ['CS304'],
    publicationsCount: 48,
    rating: 4.95,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  },
  {
    id: 'fac-003',
    employeeId: 'FAC-ECE-003',
    name: 'Dr. Rajesh Nair',
    email: 'rajesh.nair@luminous.edu',
    department: 'Electronics & Communication Engineering',
    designation: 'Head of Department',
    specialization: 'Embedded Systems & Very-Large-Scale Integration (VLSI)',
    officeRoom: 'ECE Block Room 210',
    phone: '+91 98452 14992',
    status: 'Active',
    coursesTaught: ['EC204'],
    publicationsCount: 27,
    rating: 4.8,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  },
  {
    id: 'fac-004',
    employeeId: 'FAC-MECH-004',
    name: 'Prof. Robert Taylor',
    email: 'robert.taylor@luminous.edu',
    department: 'Mechanical Engineering',
    designation: 'Head of Department',
    specialization: 'Robotics Controls & Autonomous Mechatronics',
    officeRoom: 'Mech Pavilion 105',
    phone: '+91 98801 13442',
    status: 'Active',
    coursesTaught: ['ME310'],
    publicationsCount: 22,
    rating: 4.7,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
  },
  {
    id: 'fac-005',
    employeeId: 'FAC-CIVIL-005',
    name: 'Dr. Ananya Roy',
    email: 'ananya.roy@luminous.edu',
    department: 'Civil & Environmental Engineering',
    designation: 'Head of Department',
    specialization: 'Smart Structural Engineering & Earthquake Dynamics',
    officeRoom: 'Civil Wing Room 304',
    phone: '+91 98454 12771',
    status: 'Active',
    coursesTaught: ['CE402'],
    publicationsCount: 19,
    rating: 4.85,
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
  },
];

export const INITIAL_STUDENTS: StudentRecord[] = [
  {
    id: 'std-001',
    rollNumber: 'CS23B042',
    name: 'Aanya Patel',
    email: 'aanya.patel@luminous.edu',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'A',
    cgpa: 9.28,
    attendancePercentage: 96,
    guardianName: 'Rajesh Patel',
    guardianPhone: '+91 98454 15882',
    guardianEmail: 'rajesh.patel@gmail.com',
    status: 'Active',
    enrolledCourses: ['CS301', 'CS304', 'CS309'],
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    medicalNotes: 'No known allergies. Blood Type O+',
    address: 'Campus Hostel Block B, Room 304',
  },
  {
    id: 'std-002',
    rollNumber: 'CS23B043',
    name: 'Rohan Sengupta',
    email: 'rohan.sengupta@luminous.edu',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'A',
    cgpa: 8.75,
    attendancePercentage: 88,
    guardianName: 'Dr. Debasish Sengupta',
    guardianPhone: '+91 98805 15992',
    guardianEmail: 'd.sengupta@outlook.com',
    status: 'Active',
    enrolledCourses: ['CS301', 'CS304', 'CS309'],
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    medicalNotes: 'Asthmatic - carries inhaler',
    address: 'Campus Hostel Block A, Room 112',
  },
  {
    id: 'std-003',
    rollNumber: 'CS23B044',
    name: 'Priya Sharma',
    email: 'priya.sharma@luminous.edu',
    department: 'Computer Science & Engineering',
    semester: 6,
    section: 'A',
    cgpa: 9.10,
    attendancePercentage: 94,
    guardianName: 'Sunil Sharma',
    guardianPhone: '+91 98456 15773',
    guardianEmail: 'sunil.sharma@yahoo.com',
    status: 'Active',
    enrolledCourses: ['CS301', 'CS304', 'CS309'],
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    medicalNotes: 'None',
    address: 'Off-campus Residence, West Avenue',
  },
  {
    id: 'std-004',
    rollNumber: 'AI23B012',
    name: 'Kabir Mehta',
    email: 'kabir.mehta@luminous.edu',
    department: 'Artificial Intelligence & Data Science',
    semester: 6,
    section: 'B',
    cgpa: 8.42,
    attendancePercentage: 72, // low attendance alert
    guardianName: 'Vikram Mehta',
    guardianPhone: '+91 98807 15334',
    guardianEmail: 'vikram.mehta@corp.com',
    status: 'Active',
    enrolledCourses: ['CS304', 'CS301'],
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    medicalNotes: 'Lactose intolerance',
    address: 'Campus Hostel Block B, Room 201',
  },
  {
    id: 'std-005',
    rollNumber: 'EC24B008',
    name: 'Sneha Krishnan',
    email: 'sneha.krishnan@luminous.edu',
    department: 'Electronics & Communication Engineering',
    semester: 4,
    section: 'A',
    cgpa: 9.50,
    attendancePercentage: 98,
    guardianName: 'Ramesh Krishnan',
    guardianPhone: '+91 98458 15449',
    guardianEmail: 'ramesh.k@gmail.com',
    status: 'Active',
    enrolledCourses: ['EC204'],
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150',
    medicalNotes: 'None',
    address: 'Campus Hostel Block C, Room 405',
  },
  {
    id: 'std-006',
    rollNumber: 'ME23B019',
    name: 'Arjun Deshmukh',
    email: 'arjun.deshmukh@luminous.edu',
    department: 'Mechanical Engineering',
    semester: 6,
    section: 'A',
    cgpa: 7.95,
    attendancePercentage: 81,
    guardianName: 'Prakash Deshmukh',
    guardianPhone: '+91 98809 15667',
    guardianEmail: 'prakash.d@gmail.com',
    status: 'Active',
    enrolledCourses: ['ME310'],
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150',
    medicalNotes: 'Penicillin Allergy',
    address: 'Off-campus Residence, South Square',
  },
  {
    id: 'std-007',
    rollNumber: 'CE22B005',
    name: 'Dia Fernandez',
    email: 'dia.fernandez@luminous.edu',
    department: 'Civil & Environmental Engineering',
    semester: 8,
    section: 'A',
    cgpa: 9.05,
    attendancePercentage: 92,
    guardianName: 'Carlos Fernandez',
    guardianPhone: '+91 98450 15112',
    guardianEmail: 'carlos.f@domain.com',
    status: 'Active',
    enrolledCourses: ['CE402'],
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    medicalNotes: 'None',
    address: 'Campus Hostel Block C, Room 102',
  },
];

export const INITIAL_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  {
    id: 'att-001',
    date: '2026-08-21',
    courseCode: 'CS301',
    courseName: 'Distributed Systems & Cloud Architecture',
    batch: 'CSE-2023-Sem6',
    totalStudents: 3,
    presentCount: 3,
    absentCount: 0,
    lateCount: 0,
    markedBy: 'Prof. Sarah Jenkins',
    status: 'Submitted',
    studentLogs: [
      { studentId: 'std-001', rollNumber: 'CS23B042', studentName: 'Aanya Patel', status: 'present' },
      { studentId: 'std-002', rollNumber: 'CS23B043', studentName: 'Rohan Sengupta', status: 'present' },
      { studentId: 'std-003', rollNumber: 'CS23B044', studentName: 'Priya Sharma', status: 'present' },
    ],
  },
  {
    id: 'att-002',
    date: '2026-08-21',
    courseCode: 'CS304',
    courseName: 'Artificial Intelligence & Neural Networks',
    batch: 'AI-2023-Sem6',
    totalStudents: 2,
    presentCount: 1,
    absentCount: 1,
    lateCount: 0,
    markedBy: 'Dr. Evelyn Vance',
    status: 'Submitted',
    studentLogs: [
      { studentId: 'std-001', rollNumber: 'CS23B042', studentName: 'Aanya Patel', status: 'present' },
      { studentId: 'std-004', rollNumber: 'AI23B012', studentName: 'Kabir Mehta', status: 'absent', remarks: 'Medical Leave' },
    ],
  },
];

export const INITIAL_EXAMS: ExamSchedule[] = [
  {
    id: 'ex-001',
    examCode: 'EXAM-CS301-MID',
    courseCode: 'CS301',
    courseName: 'Distributed Systems & Cloud Architecture',
    department: 'Computer Science & Engineering',
    type: 'Mid-Term',
    date: '2026-09-15',
    timeSlot: '09:30 AM - 11:30 AM',
    duration: '2 Hours',
    room: 'Tech Examination Hall A',
    totalMarks: 50,
    status: 'Upcoming',
  },
  {
    id: 'ex-002',
    examCode: 'EXAM-CS304-MID',
    courseCode: 'CS304',
    courseName: 'Artificial Intelligence & Neural Networks',
    department: 'Artificial Intelligence & Data Science',
    type: 'Mid-Term',
    date: '2026-09-18',
    timeSlot: '09:30 AM - 11:30 AM',
    duration: '2 Hours',
    room: 'AI Examination Hall B',
    totalMarks: 50,
    status: 'Upcoming',
  },
  {
    id: 'ex-003',
    examCode: 'EXAM-CS301-SEM5',
    courseCode: 'CS201',
    courseName: 'Data Structures & Algorithms (Sem 5)',
    department: 'Computer Science & Engineering',
    type: 'Final Semester',
    date: '2026-05-20',
    timeSlot: '10:00 AM - 01:00 PM',
    duration: '3 Hours',
    room: 'Main Auditorium',
    totalMarks: 100,
    status: 'Grades Published',
    grades: [
      { id: 'g-1', studentId: 'std-001', studentName: 'Aanya Patel', rollNumber: 'CS23B042', courseCode: 'CS201', score: 96, maxScore: 100, grade: 'A+', remarks: 'Top Rank' },
      { id: 'g-2', studentId: 'std-002', studentName: 'Rohan Sengupta', rollNumber: 'CS23B043', courseCode: 'CS201', score: 88, maxScore: 100, grade: 'A' },
      { id: 'g-3', studentId: 'std-003', studentName: 'Priya Sharma', rollNumber: 'CS23B044', courseCode: 'CS201', score: 92, maxScore: 100, grade: 'A+' },
    ],
  },
];

export const INITIAL_TIMETABLE_SLOTS: TimetableSlot[] = [
  // ================= CSE SEMESTER 6 =================
  {
    id: 'tt-cse6-1',
    day: 'Monday',
    timeSlot: '09:00 - 10:15 AM',
    courseCode: 'CS301',
    courseName: 'Distributed Systems & Cloud Architecture',
    instructor: 'Prof. Sarah Jenkins',
    room: 'Tech Hall 102',
    batch: 'CSE-Sem6-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-cse6-2',
    day: 'Monday',
    timeSlot: '01:00 - 02:30 PM',
    courseCode: 'CS309',
    courseName: 'Cyber Security Lab',
    instructor: 'Prof. Sarah Jenkins',
    room: 'Cyber Lab B',
    batch: 'CSE-Sem6-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-cse6-3',
    day: 'Tuesday',
    timeSlot: '10:30 - 12:00 PM',
    courseCode: 'CS306',
    courseName: 'Compiler Design & Optimization',
    instructor: 'Dr. Evelyn Vance',
    room: 'Tech Hall 104',
    batch: 'CSE-Sem6-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-cse6-4',
    day: 'Tuesday',
    timeSlot: '02:00 - 03:30 PM',
    courseCode: 'CS312',
    courseName: 'Web Services & Microservices Lab',
    instructor: 'Prof. Sarah Jenkins',
    room: 'Cloud Lab 1',
    batch: 'CSE-Sem6-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-cse6-5',
    day: 'Wednesday',
    timeSlot: '11:00 - 12:30 PM',
    courseCode: 'CS301',
    courseName: 'Distributed Systems Practical Lab',
    instructor: 'Prof. Sarah Jenkins',
    room: 'Cloud Lab 1',
    batch: 'CSE-Sem6-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-cse6-6',
    day: 'Thursday',
    timeSlot: '09:30 - 10:45 AM',
    courseCode: 'CS308',
    courseName: 'Software Engineering & Agile DevOps',
    instructor: 'Dr. Rajesh Nair',
    room: 'Tech Hall 102',
    batch: 'CSE-Sem6-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-cse6-7',
    day: 'Friday',
    timeSlot: '01:00 - 04:00 PM',
    courseCode: 'CS309',
    courseName: 'Cyber Forensics & Penetration Testing',
    instructor: 'Prof. Sarah Jenkins',
    room: 'Cyber Lab B',
    batch: 'CSE-Sem6-SecA',
    type: 'Tutorial',
  },

  // ================= CSE SEMESTER 4 =================
  {
    id: 'tt-cse4-1',
    day: 'Monday',
    timeSlot: '09:00 - 10:15 AM',
    courseCode: 'CS201',
    courseName: 'Design & Analysis of Algorithms',
    instructor: 'Dr. Ananya Roy',
    room: 'Tech Hall 101',
    batch: 'CSE-Sem4-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-cse4-2',
    day: 'Monday',
    timeSlot: '02:00 - 03:30 PM',
    courseCode: 'CS205',
    courseName: 'Operating Systems Kernel Lab',
    instructor: 'Dr. Rajesh Nair',
    room: 'Tech Lab 2',
    batch: 'CSE-Sem4-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-cse4-3',
    day: 'Tuesday',
    timeSlot: '10:30 - 11:45 AM',
    courseCode: 'CS203',
    courseName: 'Database Management Systems',
    instructor: 'Dr. Evelyn Vance',
    room: 'Tech Hall 103',
    batch: 'CSE-Sem4-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-cse4-4',
    day: 'Wednesday',
    timeSlot: '09:00 - 10:15 AM',
    courseCode: 'CS207',
    courseName: 'Computer Organization & Architecture',
    instructor: 'Dr. Rajesh Nair',
    room: 'Tech Hall 101',
    batch: 'CSE-Sem4-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-cse4-5',
    day: 'Thursday',
    timeSlot: '11:00 - 12:30 PM',
    courseCode: 'CS203',
    courseName: 'DBMS SQL & Optimization Lab',
    instructor: 'Dr. Evelyn Vance',
    room: 'Tech Lab 3',
    batch: 'CSE-Sem4-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-cse4-6',
    day: 'Friday',
    timeSlot: '10:00 - 11:30 AM',
    courseCode: 'CS209',
    courseName: 'Theory of Computation & Automata',
    instructor: 'Prof. Sarah Jenkins',
    room: 'Tech Hall 101',
    batch: 'CSE-Sem4-SecA',
    type: 'Tutorial',
  },

  // ================= CSE SEMESTER 2 =================
  {
    id: 'tt-cse2-1',
    day: 'Monday',
    timeSlot: '09:00 - 10:15 AM',
    courseCode: 'CS102',
    courseName: 'Data Structures in C/C++',
    instructor: 'Dr. Rajesh Nair',
    room: 'Science Block 101',
    batch: 'CSE-Sem2-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-cse2-2',
    day: 'Tuesday',
    timeSlot: '11:00 - 12:30 PM',
    courseCode: 'CS104',
    courseName: 'Digital Electronics Fundamentals',
    instructor: 'Dr. Rajesh Nair',
    room: 'ECE Hall 102',
    batch: 'CSE-Sem2-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-cse2-3',
    day: 'Wednesday',
    timeSlot: '02:00 - 03:30 PM',
    courseCode: 'CS102',
    courseName: 'Data Structures Hands-on Lab',
    instructor: 'Dr. Rajesh Nair',
    room: 'Computing Lab A',
    batch: 'CSE-Sem2-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-cse2-4',
    day: 'Thursday',
    timeSlot: '09:30 - 10:45 AM',
    courseCode: 'MA102',
    courseName: 'Engineering Mathematics II',
    instructor: 'Dr. Evelyn Vance',
    room: 'Science Block 102',
    batch: 'CSE-Sem2-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-cse2-5',
    day: 'Friday',
    timeSlot: '10:30 - 12:00 PM',
    courseCode: 'PH102',
    courseName: 'Applied Physics for Computing',
    instructor: 'Dr. Ananya Roy',
    room: 'Physics Lab 1',
    batch: 'CSE-Sem2-SecA',
    type: 'Lab',
  },

  // ================= CSE SEMESTER 8 =================
  {
    id: 'tt-cse8-1',
    day: 'Monday',
    timeSlot: '10:00 - 11:30 AM',
    courseCode: 'CS401',
    courseName: 'High Performance Computing & GPU Architecture',
    instructor: 'Prof. Sarah Jenkins',
    room: 'Tech Hall 301',
    batch: 'CSE-Sem8-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-cse8-2',
    day: 'Tuesday',
    timeSlot: '02:00 - 05:00 PM',
    courseCode: 'CS490',
    courseName: 'Capstone Project Review & Mentorship',
    instructor: 'Faculty Advisory Panel',
    room: 'Innovation Hub',
    batch: 'CSE-Sem8-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-cse8-3',
    day: 'Wednesday',
    timeSlot: '10:00 - 11:30 AM',
    courseCode: 'CS405',
    courseName: 'Large Language Models & GenAI Systems',
    instructor: 'Dr. Evelyn Vance',
    room: 'Tech Hall 301',
    batch: 'CSE-Sem8-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-cse8-4',
    day: 'Thursday',
    timeSlot: '01:00 - 02:30 PM',
    courseCode: 'CS409',
    courseName: 'Quantum Computing & Post-Quantum Cryptography',
    instructor: 'Prof. Sarah Jenkins',
    room: 'Tech Hall 301',
    batch: 'CSE-Sem8-SecA',
    type: 'Tutorial',
  },
  {
    id: 'tt-cse8-5',
    day: 'Friday',
    timeSlot: '09:00 - 12:00 PM',
    courseCode: 'CS492',
    courseName: 'Industry Thesis & Colloquium Seminar',
    instructor: 'Prof. Sarah Jenkins',
    room: 'Seminar Hall A',
    batch: 'CSE-Sem8-SecA',
    type: 'Lecture',
  },

  // ================= AI-DS SEMESTER 6 =================
  {
    id: 'tt-ai6-1',
    day: 'Monday',
    timeSlot: '10:30 - 11:45 AM',
    courseCode: 'AI301',
    courseName: 'Deep Learning & Neural Networks',
    instructor: 'Dr. Evelyn Vance',
    room: 'AI Lab 3',
    batch: 'AI-DS-Sem6-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-ai6-2',
    day: 'Tuesday',
    timeSlot: '10:30 - 12:00 PM',
    courseCode: 'AI304',
    courseName: 'Computer Vision & Multi-Modal Models',
    instructor: 'Dr. Evelyn Vance',
    room: 'AI Lab 3',
    batch: 'AI-DS-Sem6-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-ai6-3',
    day: 'Wednesday',
    timeSlot: '09:00 - 10:30 AM',
    courseCode: 'AI306',
    courseName: 'Natural Language Processing with Transformers',
    instructor: 'Dr. Evelyn Vance',
    room: 'AI Lab 2',
    batch: 'AI-DS-Sem6-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-ai6-4',
    day: 'Thursday',
    timeSlot: '10:30 - 12:00 PM',
    courseCode: 'AI304',
    courseName: 'PyTorch & GPU Acceleration Practical',
    instructor: 'Dr. Evelyn Vance',
    room: 'AI Lab 3',
    batch: 'AI-DS-Sem6-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-ai6-5',
    day: 'Friday',
    timeSlot: '02:00 - 04:00 PM',
    courseCode: 'AI308',
    courseName: 'Reinforcement Learning Simulation',
    instructor: 'Prof. Robert Taylor',
    room: 'Robotics Bay 1',
    batch: 'AI-DS-Sem6-SecA',
    type: 'Lab',
  },

  // ================= AI-DS SEMESTER 4 =================
  {
    id: 'tt-ai4-1',
    day: 'Monday',
    timeSlot: '09:00 - 10:15 AM',
    courseCode: 'AI201',
    courseName: 'Probability & Statistical Inference',
    instructor: 'Dr. Evelyn Vance',
    room: 'AI Hall 1',
    batch: 'AI-DS-Sem4-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-ai4-2',
    day: 'Tuesday',
    timeSlot: '01:00 - 02:30 PM',
    courseCode: 'AI203',
    courseName: 'Classical Machine Learning Algorithms',
    instructor: 'Dr. Evelyn Vance',
    room: 'AI Lab 1',
    batch: 'AI-DS-Sem4-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-ai4-3',
    day: 'Wednesday',
    timeSlot: '11:00 - 12:30 PM',
    courseCode: 'AI203',
    courseName: 'Scikit-Learn & Feature Engineering Lab',
    instructor: 'Dr. Evelyn Vance',
    room: 'AI Lab 1',
    batch: 'AI-DS-Sem4-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-ai4-4',
    day: 'Thursday',
    timeSlot: '09:00 - 10:15 AM',
    courseCode: 'AI205',
    courseName: 'Big Data Processing & Distributed Analytics',
    instructor: 'Prof. Sarah Jenkins',
    room: 'AI Hall 1',
    batch: 'AI-DS-Sem4-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-ai4-5',
    day: 'Friday',
    timeSlot: '11:00 - 12:30 PM',
    courseCode: 'AI207',
    courseName: 'Mathematical Optimization for AI',
    instructor: 'Dr. Rajesh Nair',
    room: 'AI Hall 1',
    batch: 'AI-DS-Sem4-SecA',
    type: 'Tutorial',
  },

  // ================= ECE SEMESTER 4 =================
  {
    id: 'tt-ece4-1',
    day: 'Monday',
    timeSlot: '10:30 - 11:45 AM',
    courseCode: 'EC204',
    courseName: 'Embedded Systems & IoT Hardware',
    instructor: 'Dr. Rajesh Nair',
    room: 'ECE Hall 204',
    batch: 'ECE-Sem4-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-ece4-2',
    day: 'Tuesday',
    timeSlot: '09:00 - 10:15 AM',
    courseCode: 'EC202',
    courseName: 'Signals & Systems Analysis',
    instructor: 'Dr. Rajesh Nair',
    room: 'ECE Hall 201',
    batch: 'ECE-Sem4-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-ece4-3',
    day: 'Wednesday',
    timeSlot: '02:00 - 03:30 PM',
    courseCode: 'EC204',
    courseName: 'ARM Microcontroller & IoT Workbench',
    instructor: 'Dr. Rajesh Nair',
    room: 'Embedded Lab 1',
    batch: 'ECE-Sem4-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-ece4-4',
    day: 'Thursday',
    timeSlot: '11:00 - 12:15 PM',
    courseCode: 'EC206',
    courseName: 'Analog Circuit Design & Amplifiers',
    instructor: 'Dr. Rajesh Nair',
    room: 'ECE Hall 204',
    batch: 'ECE-Sem4-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-ece4-5',
    day: 'Friday',
    timeSlot: '09:00 - 11:00 AM',
    courseCode: 'EC208',
    courseName: 'VLSI Circuit Simulation Lab',
    instructor: 'Dr. Rajesh Nair',
    room: 'VLSI Lab',
    batch: 'ECE-Sem4-SecA',
    type: 'Lab',
  },

  // ================= ECE SEMESTER 6 =================
  {
    id: 'tt-ece6-1',
    day: 'Monday',
    timeSlot: '09:00 - 10:15 AM',
    courseCode: 'EC301',
    courseName: 'Wireless Communications & 5G MIMO',
    instructor: 'Dr. Rajesh Nair',
    room: 'ECE Hall 301',
    batch: 'ECE-Sem6-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-ece6-2',
    day: 'Tuesday',
    timeSlot: '11:00 - 12:30 PM',
    courseCode: 'EC305',
    courseName: 'Digital Signal Processing DSP Lab',
    instructor: 'Dr. Rajesh Nair',
    room: 'DSP Lab',
    batch: 'ECE-Sem6-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-ece6-3',
    day: 'Wednesday',
    timeSlot: '10:00 - 11:15 AM',
    courseCode: 'EC303',
    courseName: 'Electromagnetic Wave Propagation',
    instructor: 'Dr. Rajesh Nair',
    room: 'ECE Hall 301',
    batch: 'ECE-Sem6-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-ece6-4',
    day: 'Thursday',
    timeSlot: '02:00 - 03:30 PM',
    courseCode: 'EC307',
    courseName: 'Optoelectronics & Fiber Optics Lab',
    instructor: 'Dr. Rajesh Nair',
    room: 'Optics Lab',
    batch: 'ECE-Sem6-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-ece6-5',
    day: 'Friday',
    timeSlot: '10:30 - 12:00 PM',
    courseCode: 'EC309',
    courseName: 'Microwave Engineering Tutorial',
    instructor: 'Dr. Rajesh Nair',
    room: 'ECE Hall 301',
    batch: 'ECE-Sem6-SecA',
    type: 'Tutorial',
  },

  // ================= MECH SEMESTER 6 =================
  {
    id: 'tt-mech6-1',
    day: 'Monday',
    timeSlot: '11:00 - 12:15 PM',
    courseCode: 'ME301',
    courseName: 'Applied Thermodynamics & Heat Transfer',
    instructor: 'Prof. Robert Taylor',
    room: 'Mech Hall 201',
    batch: 'MECH-Sem6-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-mech6-2',
    day: 'Tuesday',
    timeSlot: '02:00 - 03:30 PM',
    courseCode: 'ME310',
    courseName: 'Robotics & Automation Systems',
    instructor: 'Prof. Robert Taylor',
    room: 'Robotics Bay 1',
    batch: 'MECH-Sem6-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-mech6-3',
    day: 'Wednesday',
    timeSlot: '09:00 - 10:15 AM',
    courseCode: 'ME304',
    courseName: 'Fluid Mechanics & Turbomachinery',
    instructor: 'Prof. Robert Taylor',
    room: 'Mech Hall 201',
    batch: 'MECH-Sem6-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-mech6-4',
    day: 'Thursday',
    timeSlot: '01:00 - 03:00 PM',
    courseCode: 'ME310',
    courseName: 'Robotics PLC & Actuators Lab',
    instructor: 'Prof. Robert Taylor',
    room: 'Robotics Bay 1',
    batch: 'MECH-Sem6-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-mech6-5',
    day: 'Friday',
    timeSlot: '11:00 - 01:00 PM',
    courseCode: 'ME308',
    courseName: 'CAD/CAM Prototyping & CNC Lab',
    instructor: 'Prof. Robert Taylor',
    room: 'Machine Shop A',
    batch: 'MECH-Sem6-SecA',
    type: 'Lab',
  },

  // ================= CIVIL SEMESTER 8 =================
  {
    id: 'tt-civ8-1',
    day: 'Monday',
    timeSlot: '09:00 - 10:15 AM',
    courseCode: 'CE401',
    courseName: 'Earthquake Engineering & Seismic Design',
    instructor: 'Dr. Ananya Roy',
    room: 'Civil Hall 101',
    batch: 'CIVIL-Sem8-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-civ8-2',
    day: 'Tuesday',
    timeSlot: '11:00 - 12:15 PM',
    courseCode: 'CE403',
    courseName: 'Environmental Impact & Green Buildings',
    instructor: 'Dr. Ananya Roy',
    room: 'Civil Hall 101',
    batch: 'CIVIL-Sem8-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-civ8-3',
    day: 'Wednesday',
    timeSlot: '09:00 - 10:30 AM',
    courseCode: 'CE402',
    courseName: 'Smart Infrastructure & Structural Dynamics',
    instructor: 'Dr. Ananya Roy',
    room: 'Civil Design Lab',
    batch: 'CIVIL-Sem8-SecA',
    type: 'Lecture',
  },
  {
    id: 'tt-civ8-4',
    day: 'Thursday',
    timeSlot: '02:00 - 04:00 PM',
    courseCode: 'CE402',
    courseName: 'Structural Dynamics Simulation & IoT Lab',
    instructor: 'Dr. Ananya Roy',
    room: 'Civil Design Lab',
    batch: 'CIVIL-Sem8-SecA',
    type: 'Lab',
  },
  {
    id: 'tt-civ8-5',
    day: 'Friday',
    timeSlot: '10:00 - 11:30 AM',
    courseCode: 'CE408',
    courseName: 'Urban Planning & Transit Design',
    instructor: 'Dr. Ananya Roy',
    room: 'Civil Hall 101',
    batch: 'CIVIL-Sem8-SecA',
    type: 'Tutorial',
  },
];
