import {
  HostelBuilding,
  HostelRoom,
  HostelMaintenanceRequest,
  HostelIncident,
  TransportRoute,
  TransportVehicle,
  TransportPass,
  TransportAdvisory,
  Complaint,
  PlacementCompany,
  PlacementDrive,
  PlacementApplication,
  WellbeingCheckIn,
  AggregatedWellbeingMetric,
  CounselorContact,
} from '../types';

export const INITIAL_HOSTEL_BUILDINGS: HostelBuilding[] = [
  {
    id: 'bld-a',
    name: 'Block A — Senior Boys Tower',
    code: 'HST-A',
    gender: 'Boys',
    totalRooms: 120,
    totalBeds: 240,
    occupiedBeds: 228,
    wardenName: 'Major Alok Verma',
    wardenPhone: '+91 98450 14991',
    amenities: ['Gigabit Wi-Fi', 'Gymnasium', 'Study Lounge', 'Laundry Service', 'Solar Water Heating'],
  },
  {
    id: 'bld-b',
    name: 'Block B — Girls Residential Quad',
    code: 'HST-B',
    gender: 'Girls',
    totalRooms: 100,
    totalBeds: 200,
    occupiedBeds: 192,
    wardenName: 'Col. Rajeshwari Devi',
    wardenPhone: '+91 98805 14662',
    amenities: ['Biometric Access', 'Indoor Recreation', '24/7 Security Desk', 'Reading Room', 'Organic Kitchenette'],
  },
  {
    id: 'bld-c',
    name: 'Block C — Junior Girls Hall',
    code: 'HST-C',
    gender: 'Girls',
    totalRooms: 80,
    totalBeds: 160,
    occupiedBeds: 148,
    wardenName: 'Dr. Meenakshi Sundaram',
    wardenPhone: '+91 98452 14773',
    amenities: ['High-speed Wi-Fi', '24/7 Medical Attendant', 'Computer Lab', 'Laundromat'],
  },
  {
    id: 'bld-d',
    name: 'Block D — Freshers Boys Residency',
    code: 'HST-D',
    gender: 'Boys',
    totalRooms: 150,
    totalBeds: 300,
    occupiedBeds: 285,
    wardenName: 'Prof. Suresh Nair',
    wardenPhone: '+91 98803 14884',
    amenities: ['Basketball Court', 'Cafeteria Wing', 'Study Hall', 'CCTV Corridor Coverage'],
  },
];

export const INITIAL_HOSTEL_ROOMS: HostelRoom[] = [
  {
    id: 'rm-304',
    buildingCode: 'HST-B',
    roomNumber: '304',
    floor: 3,
    type: 'Double',
    capacity: 2,
    occupiedCount: 2,
    status: 'Occupied',
    occupants: [
      { studentId: 'usr-student-05', studentName: 'Aanya Patel', rollNumber: 'CS23B042', bedNumber: '304-A' },
      { studentId: 'std-102', studentName: 'Ritu Roy', rollNumber: 'CS23B049', bedNumber: '304-B' },
    ],
  },
  {
    id: 'rm-305',
    buildingCode: 'HST-B',
    roomNumber: '305',
    floor: 3,
    type: 'Double',
    capacity: 2,
    occupiedCount: 1,
    status: 'Vacant',
    occupants: [
      { studentId: 'std-108', studentName: 'Priya Sharma', rollNumber: 'AI23B011', bedNumber: '305-A' },
    ],
  },
  {
    id: 'rm-102',
    buildingCode: 'HST-A',
    roomNumber: '102',
    floor: 1,
    type: 'Single',
    capacity: 1,
    occupiedCount: 1,
    status: 'Occupied',
    occupants: [
      { studentId: 'std-201', studentName: 'Rohan Mehta', rollNumber: 'EC22B005', bedNumber: '102-A' },
    ],
  },
  {
    id: 'rm-210',
    buildingCode: 'HST-D',
    roomNumber: '210',
    floor: 2,
    type: 'Triple',
    capacity: 3,
    occupiedCount: 0,
    status: 'Under Maintenance',
    occupants: [],
  },
];

export const INITIAL_HOSTEL_MAINTENANCE: HostelMaintenanceRequest[] = [
  {
    id: 'hmt-001',
    ticketNumber: 'HMT-20260821-001',
    buildingCode: 'HST-B',
    roomNumber: '304',
    category: 'Plumbing',
    description: 'Slow drainage in bathroom sink on 3rd floor wing',
    reportedBy: 'Aanya Patel',
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    status: 'In Progress',
    priority: 'Medium',
    assignedTechnician: 'Rameshwar Plumbers',
  },
  {
    id: 'hmt-002',
    ticketNumber: 'HMT-20260820-004',
    buildingCode: 'HST-A',
    roomNumber: '102',
    category: 'Wi-Fi / Network',
    description: 'Intermittent signal drop near corner desk',
    reportedBy: 'Rohan Mehta',
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    status: 'Fixed',
    priority: 'Low',
    assignedTechnician: 'IT Support Alpha',
  },
];

export const INITIAL_HOSTEL_INCIDENTS: HostelIncident[] = [
  {
    id: 'hinc-001',
    incidentNumber: 'HINC-20260821-01',
    buildingCode: 'HST-B',
    title: 'Late Entry Past 22:30 Curfew',
    description: 'Biometric gate registered entry at 22:48 PM. Student presented permission slip signed by faculty advisor.',
    category: 'Curfew Violation',
    studentName: 'Aanya Patel',
    studentRoll: 'CS23B042',
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    status: 'Warden Under Review',
    actionTaken: 'Exemption verified by Warden Col. Rajeshwari Devi',
  },
  {
    id: 'hinc-002',
    incidentNumber: 'HINC-20260819-03',
    buildingCode: 'HST-D',
    title: 'High-Volume Speakers in Block D Common Room',
    description: 'Noise complaint filed by resident warden at 23:15 PM.',
    category: 'Noise Violation',
    reportedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    status: 'Resolved',
    actionTaken: 'Equipment turned off, warning logged',
  },
];

export const INITIAL_TRANSPORT_ROUTES: TransportRoute[] = [
  {
    id: 'rt-1',
    routeName: 'Route 1: Central Metro Express',
    routeCode: 'BUS-R1',
    startPoint: 'Central Metro Hub',
    endPoint: 'Campus Main Gate Alpha',
    stops: ['Central Metro Station', 'City Square', 'Tech Park', 'North Gate', 'Main Campus Gate'],
    departureTime: '07:30 AM',
    estimatedDuration: '35 mins',
    capacity: 50,
    subscribedCount: 44,
    assignedBusNo: 'KA-01-F-4012',
  },
  {
    id: 'rt-2',
    routeName: 'Route 2: Tech City & Suburbs Shuttle',
    routeCode: 'BUS-R2',
    startPoint: 'Silicon Valley Junction',
    endPoint: 'Campus Main Gate Alpha',
    stops: ['Silicon Valley Junction', 'Outer Ring Road', 'Residential Colony B', 'Hostel Gate South'],
    departureTime: '07:45 AM',
    estimatedDuration: '40 mins',
    capacity: 50,
    subscribedCount: 48,
    assignedBusNo: 'KA-01-F-4015',
  },
  {
    id: 'rt-3',
    routeName: 'Route 3: South Suburbs Circuit',
    routeCode: 'BUS-R3',
    startPoint: 'South Metro Station',
    endPoint: 'Campus Main Gate Alpha',
    stops: ['South Metro', 'Greenwood Park', 'University Hostel Complex'],
    departureTime: '08:00 AM',
    estimatedDuration: '25 mins',
    capacity: 45,
    subscribedCount: 38,
    assignedBusNo: 'KA-01-F-4018',
  },
];

export const INITIAL_TRANSPORT_VEHICLES: TransportVehicle[] = [
  {
    id: 'veh-1',
    busNumber: 'KA-01-F-4012',
    routeCode: 'BUS-R1',
    driverName: 'Rameshwar Singh',
    driverPhone: '+91 98450 12441',
    status: 'Active on Route',
    currentLocationStop: 'Tech Park Junction',
    nextStop: 'North Gate',
    speedKmH: 42,
    fuelLevelPercent: 84,
  },
  {
    id: 'veh-2',
    busNumber: 'KA-01-F-4015',
    routeCode: 'BUS-R2',
    driverName: 'Gurpreet Singh',
    driverPhone: '+91 98801 12442',
    status: 'Active on Route',
    currentLocationStop: 'Outer Ring Road',
    nextStop: 'Residential Colony B',
    speedKmH: 38,
    fuelLevelPercent: 76,
  },
];

export const INITIAL_TRANSPORT_PASSES: TransportPass[] = [
  {
    id: 'tpass-1',
    studentId: 'usr-student-05',
    studentName: 'Aanya Patel',
    rollNumber: 'CS23B042',
    routeCode: 'BUS-R1',
    pickupStop: 'Central Metro Station',
    validityPeriod: 'Fall Semester 2026',
    status: 'Active',
  },
];

export const INITIAL_TRANSPORT_ADVISORIES: TransportAdvisory[] = [
  {
    id: 'adv-1',
    title: 'Metro Junction Traffic Delay (10 mins)',
    routeCode: 'BUS-R1',
    message: 'Road maintenance near Central Flyover causing 10-minute transit delay for Route 1.',
    type: 'Delay',
    postedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'cmp-001',
    ticketNumber: 'CMP-20260821-0012',
    title: 'Hostel Block B Wi-Fi Router Downtime on 3rd Floor',
    description: 'Wireless access point in Block B corridor 3 disconnected intermittently during late study hours.',
    category: 'it',
    aiClassifiedCategory: 'it',
    priority: 'HIGH',
    status: 'In Progress',
    reportedBy: 'Aanya Patel',
    reporterRole: 'Student',
    assignedDepartment: 'IT Infrastructure & Digital Services',
    location: 'Hostel Block B Floor 3',
    aiSummary: 'Network connectivity drop on Hostel Block B floor 3 access point.',
    aiRecommendedActions: [
      'Reboot access point B-304',
      'Inspect POE Ethernet cable uplink',
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
  },
  {
    id: 'cmp-002',
    ticketNumber: 'CMP-20260819-0008',
    title: 'Library Air Conditioning Compressor Noise on 2nd Floor',
    description: 'Persistent rattling sound from ceiling vent causing disruption in quiet reading area.',
    category: 'infrastructure',
    aiClassifiedCategory: 'infrastructure',
    priority: 'MEDIUM',
    status: 'Resolved',
    reportedBy: 'Prof. Sarah Jenkins',
    reporterRole: 'Faculty',
    assignedDepartment: 'Facility Operations & Civil Works',
    location: 'Central Library 2nd Floor',
    aiSummary: 'HVAC unit belt vibration on library level 2.',
    aiRecommendedActions: ['Replace compressor belt and filter'],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    resolutionNotes: 'Compressor mounting damper tightened and filter replaced.',
  },
  {
    id: 'cmp-003',
    ticketNumber: 'CMP-20260818-0005',
    title: 'Bus Route 2 Morning Departure Time Adjustment Request',
    description: 'Morning shuttle departs 5 minutes early before Metro arrival schedule.',
    category: 'transport',
    aiClassifiedCategory: 'transport',
    priority: 'LOW',
    status: 'Pending',
    reportedBy: 'Aanya Patel',
    reporterRole: 'Student',
    assignedDepartment: 'Campus Transport & Logistics Desk',
    location: 'Silicon Valley Junction Stop',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: 'cmp-004',
    ticketNumber: 'CMP-20260817-0002',
    title: 'Lab 402 Workstation Software License Error',
    description: 'CAD tool failed to acquire floating network license during practical examination.',
    category: 'academic',
    aiClassifiedCategory: 'academic',
    priority: 'HIGH',
    status: 'Resolved',
    reportedBy: 'Prof. Sarah Jenkins',
    reporterRole: 'Faculty',
    assignedDepartment: 'Academic Affairs & Controller of Exams',
    location: 'Engineering Lab 402',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(),
    resolutionNotes: 'FlexLM license manager service restarted on server core.',
  },
];

export const INITIAL_PLACEMENT_COMPANIES: PlacementCompany[] = [
  {
    id: 'comp-1',
    name: 'Google DeepMind',
    industry: 'Artificial Intelligence & Research',
    website: 'https://deepmind.google',
    logoUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=120',
    tier: 'Marquee / Tech Giant',
  },
  {
    id: 'comp-2',
    name: 'Microsoft Systems',
    industry: 'Cloud Infrastructure & Enterprise Tech',
    website: 'https://microsoft.com',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120',
    tier: 'Super Dream',
  },
  {
    id: 'comp-3',
    name: 'NVIDIA AI Tech',
    industry: 'Accelerated Computing & Hardware',
    website: 'https://nvidia.com',
    logoUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=120',
    tier: 'Marquee / Tech Giant',
  },
];

export const INITIAL_PLACEMENT_DRIVES: PlacementDrive[] = [
  {
    id: 'drv-1',
    driveCode: 'DRV-2026-001',
    companyId: 'comp-1',
    companyName: 'Google DeepMind',
    jobRole: 'AI Research Engineer & Agentic Systems Specialist',
    ctcPackage: '₹48.0 LPA',
    location: 'Bangalore / Hybrid',
    driveDate: '2026-09-24',
    deadlineDate: '2026-09-15',
    minCgpa: 8.5,
    maxBacklogs: 0,
    allowedDepartments: ['Computer Science & Engineering', 'Artificial Intelligence & ML'],
    status: 'Applications Open',
    totalApplicants: 42,
  },
  {
    id: 'drv-2',
    driveCode: 'DRV-2026-002',
    companyId: 'comp-2',
    companyName: 'Microsoft Systems',
    jobRole: 'Cloud Infrastructure Associate Engineer',
    ctcPackage: '₹38.5 LPA',
    location: 'Hyderabad / Pune',
    driveDate: '2026-10-02',
    deadlineDate: '2026-09-25',
    minCgpa: 7.8,
    maxBacklogs: 1,
    allowedDepartments: ['Computer Science & Engineering', 'Artificial Intelligence & ML', 'Electronics & Comm'],
    status: 'Shortlisting',
    totalApplicants: 88,
  },
];

export const INITIAL_PLACEMENT_APPLICATIONS: PlacementApplication[] = [
  {
    id: 'app-001',
    driveId: 'drv-1',
    companyName: 'Google DeepMind',
    jobRole: 'AI Research Engineer',
    studentId: 'usr-student-05',
    studentName: 'Aanya Patel',
    rollNumber: 'CS23B042',
    cgpa: 9.28,
    department: 'Computer Science & Engineering',
    appliedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    status: 'Shortlisted',
  },
];

export const INITIAL_WELLBEING_CHECKINS: WellbeingCheckIn[] = [
  {
    id: 'wb-001',
    userId: 'usr-student-05',
    userRole: 'student',
    department: 'Computer Science & Engineering',
    moodRating: 4,
    energyLevel: 4,
    stressFactor: 'Exams',
    anonymousNotes: 'Preparing for mid-term lab exams.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'wb-002',
    userId: 'usr-student-02',
    userRole: 'student',
    department: 'Artificial Intelligence & ML',
    moodRating: 3,
    energyLevel: 3,
    stressFactor: 'Academics',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: 'wb-003',
    userId: 'usr-student-03',
    userRole: 'student',
    department: 'Electronics & Comm',
    moodRating: 5,
    energyLevel: 4,
    stressFactor: 'None',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
];

export const INITIAL_WELLBEING_AGGREGATED: AggregatedWellbeingMetric[] = [
  {
    department: 'Computer Science & Engineering',
    avgMood: 4.1,
    avgEnergy: 4.0,
    checkInCount: 142,
    topStressFactor: 'Exams & Placements',
  },
  {
    department: 'Artificial Intelligence & ML',
    avgMood: 3.9,
    avgEnergy: 3.8,
    checkInCount: 98,
    topStressFactor: 'Lab Submissions',
  },
  {
    department: 'Electronics & Communication',
    avgMood: 4.2,
    avgEnergy: 4.1,
    checkInCount: 110,
    topStressFactor: 'Mid-term Projects',
  },
];

export const COUNSELOR_CONTACTS: CounselorContact[] = [
  {
    id: 'csl-1',
    name: 'Dr. Ananya Sen',
    designation: 'Senior Institutional Psychologist & Student Counselor',
    specialty: 'Academic Stress, Mindfulness & Youth Guidance',
    availabilityHours: 'Mon - Fri: 09:00 AM - 05:00 PM',
    officeLocation: 'Wellness Center Room 104, Student Union Block',
    phone: '+91 80 2360 0199',
    email: 'counselor@luminous.edu',
  },
  {
    id: 'csl-2',
    name: 'Prof. Michael Brooks',
    designation: 'Residential Warden & Peer Support Coordinator',
    specialty: 'Hostel Adaptation & Peer Support Mentorship',
    availabilityHours: '24/7 On-Call Emergency Peer Support',
    officeLocation: 'Hostel Block B Administration Desk',
    phone: '+91 80 2360 0198',
    email: 'mbrooks.wellness@luminous.edu',
  },
];
