import {
  UserProfile,
  Incident,
  EmergencyAlert,
  SystemNotification,
  CampusLocation,
  AISafetyInsight,
  SecurityPatrolLog,
  AuditLogEntry,
  VisitorPass,
} from '../types';

export const DEMO_USERS: Record<string, UserProfile> = {
  super_admin: {
    id: 'usr-super-admin-01',
    email: 'superadmin@luminous.edu',
    full_name: 'Dr. Evelyn Vance',
    role: 'super_admin',
    department: 'Executive Chancellor Office',
    phone: '+91 98450 19283',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    emergency_contact: {
      name: 'Robert Vance',
      relationship: 'Spouse',
      phone: '+91 98450 19284',
    },
    is_active: true,
  },
  admin: {
    id: 'usr-admin-02',
    email: 'admin@luminous.edu',
    full_name: 'Marcus Chen',
    role: 'admin',
    department: 'Campus Operations & Safety Admin',
    phone: '+91 98801 18992',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    emergency_contact: {
      name: 'Linda Chen',
      relationship: 'Spouse',
      phone: '+91 98801 18993',
    },
    is_active: true,
  },
  security: {
    id: 'usr-security-03',
    email: 'security@luminous.edu',
    full_name: 'Officer Vikram Sharma',
    role: 'security',
    department: 'Campus Security & Rapid Response',
    phone: '+91 98452 17448',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    emergency_contact: {
      name: 'Pooja Sharma',
      relationship: 'Spouse',
      phone: '+91 98452 17449',
    },
    is_active: true,
  },
  faculty: {
    id: 'usr-faculty-04',
    email: 'faculty@luminous.edu',
    full_name: 'Prof. Sarah Jenkins',
    role: 'faculty',
    department: 'Computer Science & Engineering',
    phone: '+91 98803 16773',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    emergency_contact: {
      name: 'David Jenkins',
      relationship: 'Spouse',
      phone: '+91 98803 16774',
    },
    is_active: true,
  },
  student: {
    id: 'usr-student-05',
    email: 'student@luminous.edu',
    full_name: 'Aanya Patel',
    role: 'student',
    department: 'B.Tech Computer Science (Year 3)',
    phone: '+91 98454 15881',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    emergency_contact: {
      name: 'Rajesh Patel',
      relationship: 'Father',
      phone: '+91 98454 15882',
    },
    is_active: true,
  },
  parent: {
    id: 'usr-parent-06',
    email: 'parent@luminous.edu',
    full_name: 'Rajesh Patel',
    role: 'parent',
    department: 'Guardian of Aanya Patel (CSE-3A)',
    phone: '+91 98454 15882',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    emergency_contact: {
      name: 'Meena Patel',
      relationship: 'Spouse',
      phone: '+91 98454 15883',
    },
    is_active: true,
  },
  warden: {
    id: 'usr-warden-07',
    email: 'warden@luminous.edu',
    full_name: 'Col. Rajeshwari Devi',
    role: 'warden',
    department: 'Hostel Administration (Block B & C)',
    phone: '+91 98805 14662',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    emergency_contact: {
      name: 'Sunil Devi',
      relationship: 'Brother',
      phone: '+91 98805 14663',
    },
    is_active: true,
  },
  placement_officer: {
    id: 'usr-placement-08',
    email: 'placements@luminous.edu',
    full_name: 'Anil Deshmukh',
    role: 'placement_officer',
    department: 'Corporate Relations & Placement Cell',
    phone: '+91 98456 13559',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    emergency_contact: {
      name: 'Sunita Deshmukh',
      relationship: 'Spouse',
      phone: '+91 98456 13560',
    },
    is_active: true,
  },
};

// 10 Official Campus Locations
export const CAMPUS_LOCATIONS: CampusLocation[] = [
  {
    id: 'loc-main',
    name: 'Main Block',
    code: 'MB-01',
    sector: 'Academic',
    description: 'Central academic complex with lecture halls 101-308 and dean offices',
    coordinates: { x: 50, y: 46 },
    riskLevel: 'low',
    activeIncidentsCount: 0,
    buildingType: 'Auditorium & Classrooms',
    officerStationed: 'Officer Ramos (Post #1)',
  },
  {
    id: 'loc-eng',
    name: 'Engineering Block',
    code: 'ENG-D',
    sector: 'Academic',
    description: 'Block D Computing, Robotics, High-Voltage Power Labs & Maker Spaces',
    coordinates: { x: 30, y: 32 },
    riskLevel: 'critical',
    activeIncidentsCount: 2,
    buildingType: 'Engineering Labs & Server Hub',
    officerStationed: 'Officer Vikram Sharma (Unit Alpha)',
  },
  {
    id: 'loc-lib',
    name: 'Library',
    code: 'LIB-01',
    sector: 'Academic',
    description: 'Central University 4-tier Knowledge Commons & Study Pods',
    coordinates: { x: 48, y: 25 },
    riskLevel: 'medium',
    activeIncidentsCount: 1,
    buildingType: 'Library & Silent Commons',
    officerStationed: 'Guard Miller',
  },
  {
    id: 'loc-hostel-a',
    name: 'Hostel A',
    code: 'HST-A',
    sector: 'Residential',
    description: 'North Residential Tower A (320 student capacity)',
    coordinates: { x: 74, y: 24 },
    riskLevel: 'low',
    activeIncidentsCount: 0,
    buildingType: 'Student Residential Quad',
    officerStationed: 'Warden Unit A',
  },
  {
    id: 'loc-hostel-b',
    name: 'Hostel B',
    code: 'HST-B',
    sector: 'Residential',
    description: 'East Residential Tower B & Courtyard',
    coordinates: { x: 80, y: 48 },
    riskLevel: 'medium',
    activeIncidentsCount: 1,
    buildingType: 'Student Residential Quad',
    officerStationed: 'Col. Rajeshwari Devi / Guard Khan',
  },
  {
    id: 'loc-cafe',
    name: 'Cafeteria',
    code: 'CAF-01',
    sector: 'Services',
    description: 'Central Food Court, Dining Terrace, and Student Union',
    coordinates: { x: 62, y: 60 },
    riskLevel: 'low',
    activeIncidentsCount: 0,
    buildingType: 'Dining & Student Union',
    officerStationed: 'Officer Chen (Post #3)',
  },
  {
    id: 'loc-sports',
    name: 'Sports Complex',
    code: 'SPT-01',
    sector: 'Recreation',
    description: 'Indoor Arena, Gymnasium, Tennis Courts & Olympic Track',
    coordinates: { x: 82, y: 78 },
    riskLevel: 'low',
    activeIncidentsCount: 0,
    buildingType: 'Athletics & Gymnasium',
    officerStationed: 'Guard Singh',
  },
  {
    id: 'loc-parking',
    name: 'Parking',
    code: 'PRK-N',
    sector: 'Services',
    description: 'North & South Perimeter Parking Decks, EV charging bays',
    coordinates: { x: 18, y: 76 },
    riskLevel: 'medium',
    activeIncidentsCount: 1,
    buildingType: 'Multi-Level Parking Deck',
    officerStationed: 'Perimeter Mobile Unit #2',
  },
  {
    id: 'loc-med',
    name: 'Medical Center',
    code: 'MED-01',
    sector: 'Services',
    description: 'Campus 24/7 Health Clinic, Trauma Triage & On-Call Ambulance Bay',
    coordinates: { x: 34, y: 64 },
    riskLevel: 'low',
    activeIncidentsCount: 0,
    buildingType: 'Healthcare & Ambulance Depot',
    officerStationed: 'Paramedic Team 1',
  },
  {
    id: 'loc-admin',
    name: 'Administrative Block',
    code: 'ADM-HQ',
    sector: 'Administration',
    description: 'Chancellor Suite, Registrar, Security Operations Center (SOC) & Data Center',
    coordinates: { x: 42, y: 82 },
    riskLevel: 'high',
    activeIncidentsCount: 1,
    buildingType: 'Institutional HQ & SOC',
    officerStationed: 'SOC Chief Operator / Access Desk',
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-001',
    incident_number: 'INC-20260821-0042',
    reporter_id: 'usr-student-05',
    reporter_name: 'Aanya Patel',
    title: 'Chemical Fume Discharge in Organic Lab 302',
    description: 'Dense pungent smoke detected from fume hood after glassware breakage. Lab evacuated.',
    category: 'fire',
    severity: 'critical',
    ai_severity: 'critical',
    ai_confidence: 0.96,
    ai_summary: 'Hazardous chemical inhalation threat. Automatic fire and hazmat protocol recommended.',
    ai_recommended_actions: [
      'Evacuate Block D 3rd floor immediately',
      'Dispatch Hazmat Unit with respirator gear',
      'Isolate chemical exhaust ventilation system',
      'Notify Dean of Engineering & Campus Medical',
    ],
    ai_departments: ['Safety & Hazmat Response', 'Facility & Maintenance', 'Security'],
    location_id: 'loc-eng',
    location_name: 'Engineering Block',
    location_lat: 12.9716,
    location_lng: 77.5946,
    status: 'responding',
    priority_score: 9,
    assigned_department: 'Safety & Hazmat Response',
    assigned_to: 'usr-security-03',
    assigned_officer_name: 'Officer Vikram Sharma',
    is_anonymous: false,
    requires_immediate_response: true,
    timeline: [
      {
        id: 'tl-1',
        incident_id: 'inc-001',
        timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
        title: 'Incident Reported',
        description: 'Filed by Aanya Patel with high-urgency flag',
        actor_name: 'Aanya Patel',
        actor_role: 'Student',
        type: 'reported',
      },
      {
        id: 'tl-2',
        incident_id: 'inc-001',
        timestamp: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
        title: 'Gemini 3.7 Flash Autonomous Triage',
        description: 'Severity classified as CRITICAL (96% confidence). Hazmat protocol suggested.',
        actor_name: 'Gemini 3.7 Flash AI',
        actor_role: 'AI Engine',
        type: 'ai_triage',
      },
      {
        id: 'tl-3',
        incident_id: 'inc-001',
        timestamp: new Date(Date.now() - 1000 * 60 * 9).toISOString(),
        title: 'Hazmat Unit Dispatched',
        description: 'Officer Vikram Sharma acknowledged and deployed rapid response crew to 3rd Floor.',
        actor_name: 'Officer Vikram Sharma',
        actor_role: 'Security',
        type: 'dispatch',
      },
    ],
    created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'inc-002',
    incident_number: 'INC-20260821-0039',
    reporter_id: 'usr-faculty-04',
    reporter_name: 'Prof. Sarah Jenkins',
    title: 'Unauthorized Entry Attempt at Server Room B',
    description: 'Access badge reader repeatedly rejected unverified credential attempt at 02:15 AM near main server core.',
    category: 'suspicious_activity',
    severity: 'high',
    ai_severity: 'high',
    ai_confidence: 0.89,
    ai_summary: 'Physical security breach indicator on core IT infrastructure server farm.',
    ai_recommended_actions: [
      'Lock down Server Room B outer magnetic hatch',
      'Audit badge access logs for past 48 hours',
      'Review CCTV Feed Cam #09 corridor',
    ],
    ai_departments: ['Campus Security', 'IT Operations', 'Executive Administration'],
    location_id: 'loc-admin',
    location_name: 'Administrative Block',
    location_lat: 12.9722,
    location_lng: 77.5951,
    status: 'investigating',
    priority_score: 8,
    assigned_department: 'Campus Security',
    assigned_to: 'usr-security-03',
    assigned_officer_name: 'Officer Vikram Sharma',
    is_anonymous: false,
    requires_immediate_response: false,
    timeline: [
      {
        id: 'tl-4',
        incident_id: 'inc-002',
        timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        title: 'Sensor / Door Tamper Triggered',
        description: 'Electronic access control alert raised by Prof. Sarah Jenkins',
        actor_name: 'Prof. Sarah Jenkins',
        actor_role: 'Faculty',
        type: 'reported',
      },
      {
        id: 'tl-5',
        incident_id: 'inc-002',
        timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
        title: 'Under Investigation',
        description: 'Security officers reviewing CCTV and physical perimeter.',
        actor_name: 'Officer Vikram Sharma',
        actor_role: 'Security',
        type: 'status_change',
      },
    ],
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'inc-003',
    incident_number: 'INC-20260821-0028',
    reporter_id: 'usr-warden-07',
    reporter_name: 'Col. Rajeshwari Devi',
    title: 'Water Main Valve Leak near Hostel B Courtyard',
    description: 'Substantial pressure leak flooding outer pedestrian walkway. Slip hazard for residents.',
    category: 'infrastructure',
    severity: 'medium',
    ai_severity: 'medium',
    ai_confidence: 0.92,
    ai_summary: 'Civil infrastructure failure impacting residential transit zone.',
    ai_recommended_actions: [
      'Shut off water main isolation valve B-3',
      'Place caution barriers around puddle zone',
      'Deploy maintenance plumbing team',
    ],
    ai_departments: ['Facility & Maintenance', 'Hostel Administration'],
    location_id: 'loc-hostel-b',
    location_name: 'Hostel B',
    location_lat: 12.973,
    location_lng: 77.5938,
    status: 'acknowledged',
    priority_score: 5,
    assigned_department: 'Facility & Maintenance',
    is_anonymous: false,
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 'inc-004',
    incident_number: 'INC-20260821-0015',
    reporter_id: 'usr-student-05',
    reporter_name: 'Anonymous Student',
    title: 'Bicycle Lock Damaged at Parking Deck North',
    description: 'Found bike cable lock clipped and abandoned near rack slot #24.',
    category: 'theft',
    severity: 'low',
    ai_severity: 'low',
    ai_confidence: 0.94,
    ai_summary: 'Attempted minor property theft in perimeter vehicle enclosure.',
    ai_recommended_actions: [
      'Increase lighting checks on rack 24',
      'Log into perimeter patrol watch list',
    ],
    ai_departments: ['Perimeter Security'],
    location_id: 'loc-parking',
    location_name: 'Parking',
    status: 'resolved',
    priority_score: 2,
    assigned_department: 'Perimeter Security',
    is_anonymous: true,
    created_at: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    resolved_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'inc-005',
    incident_number: 'INC-20260820-0091',
    reporter_id: 'usr-faculty-04',
    reporter_name: 'Prof. Sarah Jenkins',
    title: 'HVAC Air Filter Failure in Library Level 2',
    description: 'Loud rattling noise and poor airflow in quiet study zone. Overheating risk for terminal banks.',
    category: 'infrastructure',
    severity: 'medium',
    ai_severity: 'medium',
    ai_confidence: 0.91,
    ai_summary: 'HVAC motor belt wear causing airflow reduction and localized thermal spike.',
    ai_recommended_actions: [
      'Replace compressor belt and filter cartridge',
      'Check circuit breakers on Level 2',
    ],
    ai_departments: ['Facility & Maintenance'],
    location_id: 'loc-lib',
    location_name: 'Library',
    status: 'investigating',
    priority_score: 4,
    assigned_department: 'Facility & Maintenance',
    is_anonymous: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
  },
  {
    id: 'inc-006',
    incident_number: 'INC-20260819-0084',
    reporter_id: 'usr-student-05',
    reporter_name: 'Aanya Patel',
    title: 'Spilled Liquid Hazard on Main Block Stairwell C',
    description: 'Slippery oily residue on concrete steps between 2nd and 3rd floors.',
    category: 'infrastructure',
    severity: 'low',
    ai_severity: 'low',
    ai_confidence: 0.95,
    location_id: 'loc-main',
    location_name: 'Main Block',
    status: 'resolved',
    priority_score: 2,
    assigned_department: 'Janitorial & Safety',
    is_anonymous: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    resolved_at: new Date(Date.now() - 1000 * 60 * 60 * 34).toISOString(),
  },
  {
    id: 'inc-007',
    incident_number: 'INC-20260817-0072',
    reporter_id: 'usr-warden-07',
    reporter_name: 'Dr. Rajeshwari Devi',
    title: 'Unauthorized Late Night Gathering at Sports Complex Bleachers',
    description: 'Group of 12 unverified individuals after 23:00 curfew. Refused initial verbal check.',
    category: 'suspicious_activity',
    severity: 'medium',
    ai_severity: 'medium',
    ai_confidence: 0.88,
    location_id: 'loc-sports',
    location_name: 'Sports Complex',
    status: 'resolved',
    priority_score: 5,
    assigned_department: 'Campus Security',
    assigned_officer_name: 'Officer Vikram Sharma',
    is_anonymous: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    resolved_at: new Date(Date.now() - 1000 * 60 * 60 * 94).toISOString(),
  },
  {
    id: 'inc-008',
    incident_number: 'INC-20260815-0061',
    reporter_id: 'usr-faculty-04',
    reporter_name: 'Prof. Sarah Jenkins',
    title: 'Power Surge & Circuit Trip in Block D Electrical Room',
    description: 'Main distribution box breaker tripped twice during heavy load computing test.',
    category: 'infrastructure',
    severity: 'high',
    ai_severity: 'high',
    ai_confidence: 0.93,
    ai_summary: 'Substation feed fluctuation causing load shedding across engineering servers.',
    ai_recommended_actions: [
      'Comprehensive electrical transformer inspection',
      'Verify thermal imaging on breaker panels',
      'Increase evening security patrol check-ins',
    ],
    ai_departments: ['Facility & Maintenance', 'Security', 'Engineering Faculty'],
    location_id: 'loc-eng',
    location_name: 'Engineering Block',
    status: 'resolved',
    priority_score: 7,
    assigned_department: 'Facility & Maintenance',
    is_anonymous: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
    resolved_at: new Date(Date.now() - 1000 * 60 * 60 * 138).toISOString(),
  },
  {
    id: 'inc-009',
    incident_number: 'INC-20260812-0055',
    reporter_id: 'usr-student-05',
    reporter_name: 'Aanya Patel',
    title: 'Exhaust Fan Bearing Seized in Block D Chem Lab 201',
    description: 'Overheating bearing emitting burning belt odor in lab ventilation shaft.',
    category: 'infrastructure',
    severity: 'medium',
    ai_severity: 'medium',
    ai_confidence: 0.94,
    location_id: 'loc-eng',
    location_name: 'Engineering Block',
    status: 'resolved',
    priority_score: 5,
    assigned_department: 'Facility & Maintenance',
    is_anonymous: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 220).toISOString(),
    resolved_at: new Date(Date.now() - 1000 * 60 * 60 * 210).toISOString(),
  },
  {
    id: 'inc-010',
    incident_number: 'INC-20260808-0048',
    reporter_id: 'usr-admin-02',
    reporter_name: 'Marcus Chen',
    title: 'Emergency Exit Door Sensor Malfunction in Block D',
    description: 'Fire exit door magnetic contact reporting open state intermittently on 1st floor.',
    category: 'infrastructure',
    severity: 'medium',
    ai_severity: 'medium',
    ai_confidence: 0.90,
    location_id: 'loc-eng',
    location_name: 'Engineering Block',
    status: 'resolved',
    priority_score: 4,
    assigned_department: 'Perimeter Security',
    is_anonymous: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 310).toISOString(),
    resolved_at: new Date(Date.now() - 1000 * 60 * 60 * 300).toISOString(),
  },
  {
    id: 'inc-011',
    incident_number: 'INC-20260804-0036',
    reporter_id: 'usr-faculty-04',
    reporter_name: 'Prof. Sarah Jenkins',
    title: 'Capacitor Bank Humming & Sparking in Engineering Sub-panel',
    description: 'Visible arcing heard during high-voltage transformer startup.',
    category: 'infrastructure',
    severity: 'high',
    ai_severity: 'high',
    ai_confidence: 0.96,
    location_id: 'loc-eng',
    location_name: 'Engineering Block',
    status: 'resolved',
    priority_score: 8,
    assigned_department: 'Facility & Maintenance',
    is_anonymous: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 410).toISOString(),
    resolved_at: new Date(Date.now() - 1000 * 60 * 60 * 395).toISOString(),
  },
  {
    id: 'inc-012',
    incident_number: 'INC-20260801-0022',
    reporter_id: 'usr-student-05',
    reporter_name: 'Anonymous Student',
    title: 'Emergency Call Box Audio Static near Cafeteria Plaza',
    description: 'Blue light station intercom distorted when pressed for safety test.',
    category: 'infrastructure',
    severity: 'low',
    ai_severity: 'low',
    ai_confidence: 0.91,
    location_id: 'loc-cafe',
    location_name: 'Cafeteria',
    status: 'resolved',
    priority_score: 3,
    assigned_department: 'IT & Telecommunications',
    is_anonymous: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 480).toISOString(),
    resolved_at: new Date(Date.now() - 1000 * 60 * 60 * 460).toISOString(),
  },
  {
    id: 'inc-013',
    incident_number: 'INC-20260728-0014',
    reporter_id: 'usr-warden-07',
    reporter_name: 'Col. Rajeshwari Devi',
    title: 'Fire Extinguisher Pressure Low in Hostel A Corridor 3',
    description: 'Monthly inspection identified 2 dry powder cylinders below required gauge pressure.',
    category: 'infrastructure',
    severity: 'medium',
    ai_severity: 'medium',
    ai_confidence: 0.97,
    location_id: 'loc-hostel-a',
    location_name: 'Hostel A',
    status: 'resolved',
    priority_score: 4,
    assigned_department: 'Safety & Hazmat Response',
    is_anonymous: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 550).toISOString(),
    resolved_at: new Date(Date.now() - 1000 * 60 * 60 * 540).toISOString(),
  },
  {
    id: 'inc-014',
    incident_number: 'INC-20260724-0008',
    reporter_id: 'usr-admin-02',
    reporter_name: 'Marcus Chen',
    title: 'Emergency Lighting Backup Battery Degraded in Medical Center',
    description: 'Routine test showed battery hold time under 45 minutes for triage wing.',
    category: 'infrastructure',
    severity: 'medium',
    ai_severity: 'medium',
    ai_confidence: 0.95,
    location_id: 'loc-med',
    location_name: 'Medical Center',
    status: 'resolved',
    priority_score: 5,
    assigned_department: 'Facility & Maintenance',
    is_anonymous: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 640).toISOString(),
    resolved_at: new Date(Date.now() - 1000 * 60 * 60 * 620).toISOString(),
  },
];

// Grounded AI Safety Intelligence Insights
export const AI_SAFETY_INSIGHTS: AISafetyInsight[] = [
  {
    id: 'insight-1',
    title: 'Block D (Engineering) Recurrent Infrastructure & Electrical Strain',
    location: 'Engineering Block (Block D)',
    pattern_description: 'Block D has experienced 7 infrastructure incidents in the last 30 days, primarily linked to lab electrical sub-panels, high-voltage circuits, and exhaust ventilation.',
    incident_count: 7,
    time_window: 'Last 30 Days',
    confidence: 0.96,
    severity: 'critical',
    recommendations: [
      'Schedule an electrical inspection and thermal imaging of all sub-panels in Block D.',
      'Increase evening security patrols (20:00 - 02:00) around ground-floor transformers.',
      'Enforce automated load shedding during peak GPU computing experiment runs.',
    ],
    action_status: 'pending',
  },
  {
    id: 'insight-2',
    title: 'Hostel B Late-Hour Resident & Visitor Congestion',
    location: 'Hostel B',
    pattern_description: '3 late-night noise and access control alerts recorded during Friday-Saturday 23:00-03:00 windows.',
    incident_count: 3,
    time_window: 'Last 7 Days',
    confidence: 0.89,
    severity: 'medium',
    recommendations: [
      'Enforce digital NFC badge checkout at outer Hostel B gate after 22:30.',
      'Station Warden Unit 2 at common courtyard intersection.',
    ],
    action_status: 'pending',
  },
  {
    id: 'insight-3',
    title: 'North Perimeter Parking Low-Light Blindspots',
    location: 'Parking',
    pattern_description: '4 minor bike lock tampering and vehicle alerts concentrated in unlit perimeter sectors.',
    incident_count: 4,
    time_window: 'Last 30 Days',
    confidence: 0.92,
    severity: 'high',
    recommendations: [
      'Deploy supplemental 4000K LED floodlights along North Deck perimeter fence.',
      'Schedule 45-minute mobile security drone sweeps between 22:00 and 05:00.',
    ],
    action_status: 'pending',
  },
];

export const INITIAL_PATROL_LOGS: SecurityPatrolLog[] = [
  {
    id: 'patrol-1',
    officer_name: 'Officer Vikram Sharma',
    unit: 'Unit Alpha',
    location_name: 'Engineering Block (Block D)',
    status: 'responding',
    last_check_in: '2 min ago',
    battery_level: 94,
  },
  {
    id: 'patrol-2',
    officer_name: 'Officer Ramos',
    unit: 'Unit Bravo',
    location_name: 'Main Block & Academic Quad',
    status: 'patrolling',
    last_check_in: '6 min ago',
    battery_level: 88,
  },
  {
    id: 'patrol-3',
    officer_name: 'Officer Khan',
    unit: 'Unit Charlie',
    location_name: 'Hostel A & B Courtyard',
    status: 'patrolling',
    last_check_in: '9 min ago',
    battery_level: 79,
  },
  {
    id: 'patrol-4',
    officer_name: 'Officer Chen',
    unit: 'Unit Delta',
    location_name: 'Cafeteria & Student Plaza',
    status: 'stationed',
    last_check_in: '14 min ago',
    battery_level: 91,
  },
  {
    id: 'patrol-5',
    officer_name: 'Perimeter Mobile Unit #2',
    unit: 'Unit Echo',
    location_name: 'Parking North Deck & Gates',
    status: 'patrolling',
    last_check_in: '4 min ago',
    battery_level: 85,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'audit-01',
    action: 'INCIDENT_AI_TRIAGED',
    actor: 'Gemini 3.7 Flash AI',
    actorRole: 'AI Engine',
    ip: '10.0.1.1 (Internal AI Mesh)',
    timestamp: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
    timeAgo: '11 min ago',
    entity: 'INC-20260821-0042',
    details: 'Severity: CRITICAL, Confidence: 96%, Suggested Hazmat protocol',
  },
  {
    id: 'audit-02',
    action: 'DISPATCH_UNIT_DEPLOYED',
    actor: 'Officer Vikram Sharma (Security)',
    actorRole: 'Security Officer',
    ip: '10.0.8.44',
    timestamp: new Date(Date.now() - 1000 * 60 * 9).toISOString(),
    timeAgo: '9 min ago',
    entity: 'INC-20260821-0042',
    details: 'Unit Alpha dispatched to Engineering Block Floor 3',
  },
  {
    id: 'audit-03',
    action: 'EMERGENCY_BROADCAST_TRANSMITTED',
    actor: 'Marcus Chen (Admin)',
    actorRole: 'Safety Admin',
    ip: '10.0.4.12',
    timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    timeAgo: '10 min ago',
    entity: 'Alert alt-001',
    details: 'Hazard warning broadcasted to 6 user roles across campus',
  },
  {
    id: 'audit-04',
    action: 'ACCESS_SENSOR_OVERRIDE_INVESTIGATED',
    actor: 'Officer Vikram Sharma (Security)',
    actorRole: 'Security Officer',
    ip: '10.0.8.44',
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    timeAgo: '35 min ago',
    entity: 'INC-20260821-0039',
    details: 'Physical verification of Server Room B in Admin Block completed',
  },
];

export const INITIAL_ALERTS: EmergencyAlert[] = [
  {
    id: 'alt-001',
    title: 'ACTIVE HAZARD PROTOCOL: Engineering Block 3rd Floor',
    message: 'All personnel and students must avoid Chemistry Building Level 3. Ventilation units engaged. Emergency responders on site.',
    type: 'evacuation',
    severity: 'critical',
    target_roles: ['super_admin', 'admin', 'faculty', 'student', 'security', 'warden'],
    is_active: true,
    created_by: 'Marcus Chen (Admin)',
    created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
];

export const INITIAL_VISITORS: VisitorPass[] = [
  {
    id: 'vis-001',
    pass_number: 'PASS-20260821-0182',
    visitor_name: 'Dr. Anita Roy',
    visitor_phone: '+91 98450 12339',
    visitor_company: 'Stanford AI Institute',
    purpose: 'Guest Keynote on Agentic Safety & Robotics',
    host_name: 'Prof. Sarah Jenkins',
    host_department: 'Computer Science & Engineering',
    destination_building: 'Main Auditorium & CS Lab 2',
    badge_id: 'VIS-SEC-A12',
    status: 'checked_in',
    check_in_time: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    gate_entry: 'Main Security Gate Alpha',
    vehicle_number: 'KA-01-EQ-9921',
    id_verified: true,
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 'vis-002',
    pass_number: 'PASS-20260821-0185',
    visitor_name: 'Robert Vance',
    visitor_phone: '+91 98450 19283',
    visitor_company: 'Apex Scientific Diagnostics',
    purpose: 'Quarterly Lab Equipment Calibration & Safety Audit',
    host_name: 'Dr. Evelyn Vance',
    host_department: 'Chancellor Office',
    destination_building: 'Engineering Block',
    badge_id: 'VIS-SEC-B04',
    status: 'checked_in',
    check_in_time: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    gate_entry: 'North Perimeter Gate',
    vehicle_number: 'MH-02-AZ-4110',
    id_verified: true,
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'vis-003',
    pass_number: 'PASS-20260821-0189',
    visitor_name: 'Farhan Siddiqui',
    visitor_phone: '+91 98452 17882',
    visitor_company: 'Infosys Campus Connect',
    purpose: 'Final Round Placement Technical Interviews',
    host_name: 'Anil Deshmukh',
    host_department: 'Placement Cell',
    destination_building: 'Administrative Block',
    badge_id: 'VIS-SEC-C08',
    status: 'expected',
    gate_entry: 'Main Security Gate Alpha',
    id_verified: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: 'vis-004',
    pass_number: 'PASS-20260821-0177',
    visitor_name: 'Meena Patel',
    visitor_phone: '+91 98454 15881',
    purpose: 'Student Guardian Consultation',
    host_name: 'Col. Rajeshwari Devi',
    host_department: 'Hostel Administration',
    destination_building: 'Hostel Block B',
    badge_id: 'VIS-SEC-D02',
    status: 'checked_out',
    check_in_time: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    check_out_time: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    gate_entry: 'South Residential Gate',
    id_verified: true,
    created_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif-001',
    title: 'Emergency Alert Broadcasted',
    message: 'Active Hazard Protocol initiated for Chemistry Block 3rd Floor.',
    type: 'emergency',
    read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    link: '/safety/command-center',
  },
  {
    id: 'notif-002',
    title: 'New Incident Dispatched',
    message: 'INC-20260821-0042 assigned to Emergency Response Team.',
    type: 'incident',
    read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
    link: '/incidents',
  },
  {
    id: 'notif-003',
    title: 'Daily Attendance Report Synced',
    message: 'CSE-Semester 6 Batch A attendance roster submitted.',
    type: 'academic',
    read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    link: '/attendance',
  },
];

